[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = 
    -std=gnu++20
    -D POLAR_HARDWARE_NODE=1
    -D SUB_ZERO_MIL_SPEC=1
